# 配置文件示例
#泪心寻找封包特征字节集
leixinTargerHeaderHex=0x00 0x00 0x0A 0x11
#泪心替换封包十六进制
leixinReplacement=0xFF 0xFF 0xAA 0xBB
#泪心替换位置 请输入十进制整数(替换)
leixinposition=50
#泪心封包递进位置数值(递进)
leixindijin=77
#当前确定是否启动发送替换方案
send=0
#请问是否启动接收替换方案
recv=1